name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install lftp
      run: sudo apt-get install lftp

    - name: Deploy to cPanel
      run: |
        FTP_USERNAME=$FTP_USERNAME
        FTP_PASSWORD=$FTP_PASSWORD
        FTP_HOST=$FTP_HOST


        lftp -d -c "open -u $FTP_USERNAME,$FTP_PASSWORD -p 21 $FTP_HOST; --exclude .git --exclude .github --exclude .gitignore"

      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_HOST: ${{ secrets.FTP_HOST }}

